version: '3'
services:
  beckend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - "beckend"